global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA2UTSYU46NPCRSHNB
        secret_key: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
        port: 9100
