global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.44.235:9090','172.31.32.143:9100','172.31.34.82:9100']
